import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Layout from '../componets/layout/layout'
import Script from 'next/script'


export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>JP-demo</title>
        <meta name="description" content="Generated by create next app" />
       <link rel="icon" href="/jpicon.ico" />
            
      </Head>
           
      <Layout className={styles.Layout}>
          <main className={styles.h1}>
            <h1 > It works!! </h1>
       
          </main>

     </Layout>
     <style jsx>{`
      .Layout{
       z-index:1;
      }
      h1{
       color:white;
       z-index:2;
     }       
   `}


     </style>
   
     
    </div>
  )
}
