import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Layout from '../componets/layout/layout'
import Image from 'next/image'
import jpicon from '../public/img/jpicon.svg'
import polygon from '../public/img/polygon.svg'


export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>JP-demo</title>
        
        <meta name="description" content="Generated by create next app" />
        
        <link rel="icon" href="/jpicon.ico" />

      </Head>
        
      <Layout>
        <main className={styles.main_container1}>
          <div className={styles.text1}>
            <p> <b>I'm</b> Juan Pablo</p>
          </div>
          <div className={styles.text2}>
            <p>Buriticá</p>
          </div>
          <div>
            <p></p>
          </div>
          <div className={styles.text3}>
            <p className={styles.test3_p}>VP of Eng @splice — I build effective distributed eng teams and latino/latam dev communities @colombia_dev, @quecharla, @jsconfco, @rubyconfco, @bogotaJS</p>
          </div>
          <div></div>
          <div></div>
        </main>

        <main className={styles.main_home_global}>
          <div className={styles.main_container}>
            <h1 className={styles.main_h1}></h1>
            <form className={styles.form_container} action="">
              <ul className={styles.ul} >Send me a message!
                <li className={styles.li_name}>Name:
                  <label htmlFor="name"></label>
                  <input type="text" name="name" id="name"/>
                </li>
                <li className={styles.li_mail}>E-mail:
                  <label htmlFor="mail"></label>
                  <input type="email" name="mail" id="mail"/>
                </li>
                <li className={styles.li_msg}>Message:
                  <label htmlFor="msg"></label>
                  <textarea className={styles.textarea} name="msg" id="msg" cols="30" rows="10"></textarea>
                </li>
                <li className={styles.send_button}>
                  <button className={styles.button} type="submit">send! 
                  <Image
                    src={polygon}
                    width = {13.89}
                    height = {15}
                  />
                  
                  </button>
                </li>
              </ul>
                <div className={styles.jp_logo}>
                  <Image
                    src={jpicon}
                    width = {43}
                    height = {38.89}
                  />
                </div>
                <div className={styles.line}>
                  
                </div>
                <div className={styles.text}>
                  <p>
                    j@buriti.ca
                  </p>

                </div>

            </form>
            
          </div>          
        </main>
      </Layout>


      

      
    </div>
  )
}
